server:
  port: 9999
  servlet:
    context-path: /admin

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    name: myData
    url: jdbc:postgresql://localhost:5432/shopping?characterEncoding=UTF-8&serverTimeZone=UTC
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    root: info
    com.lhp: debug

